### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by devorbitus** [danprince/tiny-binary-format#10]
I know that this library was designed for game development but I can see a use for it in business application as well. I recently had a screen which had numerous check-boxes that was represented by a bitmask to tell which boxes were checked and which had not been in the URL routing. The challenge came when we had to change the feature to allow for a number per selection instead of a Boolean. I was never fully happy with our approach and I would have loved to use your library on the front end to map the different selections to a single number that can be translated back to the selections. If this was in Bower it would make it much easier to have this kind of solution in our toolbox.

**Comment by danprince** [comment]
Added bower support for v0.0.2

```
bower install tiny-binary-format
```

**Comment by devorbitus** [comment]
Awesome, thanks!
